### ISSUE TITLE
请问怎么POST 文件翻译

### ISSUE THREAD

**Issue by APPX-Studio** [michaeloo0/chatgpt-doc-translator#2]
MyCode/openai/chatgpt-doc-translator']
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [5030] using StatReload
INFO:     Started server process [5036]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:51187 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51187 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51187 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51202 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51350 - "POST / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51350 - "POST //translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51360 - "POST /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51379 - "POST /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51396 - "POST /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51403 - "POST /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51403 - "POST / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51411 - "POST /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51414 - "GET /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51414 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51434 - "POST /translate HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51439 - "POST / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51439 - "POST / HTTP/1.1" 404 Not Found

**Comment by APPX-Studio** [comment]
![截屏20230513085152](https://github.com/michaeloo0/chatgpt-doc-translator/assets/49307767/f2b8c399-c5f2-4b9e-a2cc-0a05add3e7da)

**Comment by leogogog** [comment]
I have fixed the bug. Now, it can work with the following endpoint.

```
curl --request POST \
  --url http://localhost:8000/translate-file_zh \
  --form 'file=@/Users/michael/Desktop/translate-test.pdf'
```
