### ISSUE TITLE
Api key won't parse correctly

### ISSUE THREAD

**Issue by dannythunder** [michaeloo0/chatgpt-doc-translator#6]
There is a bug in `interact_llm.py` where the api key is parsed `openai.api_key = os.environ['OPENAI_API_KEY']`.

I've no experience in python lang, but looking at `temperature=float(os.environ['TEMPERATURE'])` seeing the `[' ']` i suspect it's not being parsed as a string.

I changed to `[" "]` and it worked.

Creating a pull request with some minor changes to the readme.

**Comment by leogogog** [comment]
Thanks!
